baseURL = 'https://faruq-06.github.io/Classroom/'
languageCode = 'en-us'
title = 'MHBF Classroom'
theme = "roadster"

[params]
  description = "A simple classroom site for lectures, resources, and assignments."
  author = "md Habibul Basar Faruq"

